# https://github.com/morvencao/kube-mutating-webhook-tutorial 
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: "inject-logstach-api-logger-sidecar"
webhooks:
- name: "mutateme-server.default.svc"
  namespaceSelector:
    matchLabels:
      transformers-apitest-sidecar: enabled
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["services"]
    scope:       "Namespaced"
  - operations: ["CREATE"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["deployments"]
    scope: "Namespaced"
  clientConfig:
    service:
      name: mutateme-server
      namespace: default
      path: "/mutate"    
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFtTVNRd0lnWURWUVFEREJ0dmNHVnUKYzJocFpuUXRjMmxuYm1WeVFERTFPRFUwTWpjek9Ea3dIaGNOTWpBd016STRNakF5T1RRNFdoY05NalV3TXpJMwpNakF5T1RRNVdqQW1NU1F3SWdZRFZRUUREQnR2Y0dWdWMyaHBablF0YzJsbmJtVnlRREUxT0RVME1qY3pPRGt3CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURGQm02VHRlcGVwN2lrcWMrZWhLeWoKLzJvWFhheFh0SWFCRmJNOERBYllzOUxlRFNxTkVObERRbUc5dCtVOUhuN1QwTnF3UEE5OVRwMEY3WlRnbDhoZwpmeGZTWmpuUmRTU2loUnpMeGxJZEhSc0dEUHhlWlhyY3dsNXpMdk5VNHNodW5vKy9FUTA0OHBFZTQzQXhLcmY0CkxTcmx3a0V1QW54bEZxeTdHaWNqUUhEeWtxQ3h2V1dqOFRFS3JTNkoyMDBHS0g4MGJjSElkdjN5Vk8yWnN4ZisKREh2dHZ1TVQwdklVTzBjYUZ2WG9SS0RHREdTOTUrVXRwK3ZMbzRPZkRUaytIYWppSVNlUGV4TzFReTFRb2p0OQpuNUJxSlZmRFptaUFzQnl1YzYvTWszUDZvVVpJc3lXeGc3TWo1eUFJV2ltU0VzajdjdlFlckZDcDdRRkVucEtQCkFnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQk5Xai8xWU8wK3R6RzBDclAxalZJcEcyb1huZkpFbXdBMHdIcEZKM3FrYkxwYgpsb2RsekZkajhyeHBCYU5rbXA0cStJdkVjQzdkcGE4WkkvL2g4SlV6UEdvb1BwWXM4U09ibTB0eC91eks3bXVlCkVDb1N2dldFcGxFSTZpei9Tc2liN3lrejdnSld5M0tReS9hZHp1cm9zMGtiRGo3WEJaQ1pNTWF0ZFdVdHprd1YKdk52UE12NlVNOU1TUWdlOWUwZzN5c3lib1FxN1hxV1cvdlIwOFN1VHg2VXVIS0wwdkNzMEFabUZwSnc5QktubQpHWG11WWNqWjdseFViZmV4YnJjZllFcmVSZ2hycUxlVnJWVTFXdzBFb1lENERUMm9ROXM0ZUZqVEVzRU84KzRnCkkrTjh0ay93R3Rqdm9YcDVuK1NJMTFsdW9TdFdUTFZ6bWxGeGc5REIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  failurePolicy: Fail
